### ISSUE TITLE
App store submission problem

### ISSUE THREAD

**Issue by diazod** [trywildcard/wildcard_ios_sdk#1]
I have download your framework and implemented it in the way you recommended for Objective c and  everything works fine, but when I try to submit my application to the App Store I get the following errors, I want to know if I'm doing something wrong

![screen shot 2015-08-04 at 6 36 31 pm](https://cloud.githubusercontent.com/assets/474672/9075224/f918db00-3ad7-11e5-8bf3-922320b57366.png)

**Comment by DaveX101** [comment]
Hi Seinh,

Actually this is a new requirement from Apple that when using Frameworks they must only be compiled for ARM architectures and not for Simulators(i.e. x86_64 or i386 archs) There is a separate Framework you must download for Releasing. Please read and download it here. http://www.trywildcard.com/docs/ios-sdk/faq#releasing The installation steps are exactly the same that you already went through. Thanks @Seinh

**Comment by diazod** [comment]
Oh, thank you very much, I'll try with this version
