### ISSUE TITLE
Xcode 7 and ios 9.0

### ISSUE THREAD

**Issue by diazod** [trywildcard/wildcard_ios_sdk#4]
Every time I have to run a project with wildcard on Xcode 7 beta and ios 9.0 my application crashes and get the next error message:

dyld: Symbol not found: __TMdVSS5Index
  Referenced from: /Users/daviddiaz/Library/Developer/CoreSimulator/Devices/F8289FC5-0919-4E37-894B-6C4A63B68E6D/data/Containers/Bundle/Application/8016FE53-7BCC-43C1-8FB1-2BABB15C83DC/Dagm8.app/Frameworks/WildcardSDK.framework/WildcardSDK
  Expected in: /Users/daviddiaz/Library/Developer/CoreSimulator/Devices/F8289FC5-0919-4E37-894B-6C4A63B68E6D/data/Containers/Bundle/Application/8016FE53-7BCC-43C1-8FB1-2BABB15C83DC/Dagm8.app/Frameworks/libswiftCore.dylib
 in /Users/daviddiaz/Library/Developer/CoreSimulator/Devices/F8289FC5-0919-4E37-894B-6C4A63B68E6D/data/Containers/Bundle/Application/8016FE53-7BCC-43C1-8FB1-2BABB15C83DC/Dagm8.app/Frameworks/WildcardSDK.framework/WildcardSDK

**Comment by lacyrhoades** [comment]
Hey @Seinh, thanks for the report. This was happening before we updated to Xcode 7. The project on Github is updated for XC7 now and the binaries linked in the docs are also updated! Let me know if you need any more help.
